public void testsimpledoublepresent() throws exception { args args = new args(“x##”, new string[](“-x”, “42.3”}); assertequals(1, args.cardinality()); asserttrue(args.has(‘x’)); assertequals(42.3, args.getdouble(‘x’), .001); } public void testinvaliddouble() throws exception { try { new args(“x##”, new string []{“-x”, “forty two”}); fail(); } catch (argsexception e) { assertequals(argsexception.errorcode.invalid_double, e.geterrorcode()); assertequals(‘x’, e.geterrorargumentid()); assertequals(“forty two”, e.geterrorparameter()); } } public void testmissingdouble() throws exception { try { new args(“x##”, new string[]{“-x”}); fail(); } catch (argsexception e) { assertequals(argsexception.errorcode.missing_double, e.geterrorcode()); assertequals(‘x’, e.geterrorargumentid()); } } } listado 14-14 argsexceptiontest.java. public class argsexceptiontest extends testcase { public void testunexpectedmessage() throws exception { argsexception e = new argsexception(argsexception.errorcode.unexpected_argument, ‘x’, null); assertequals(“argument -x unexpected.”, e.errormessage()); } public void testmissingstringmessage() throws exception { argsexception e = new argsexception(argsexception.errorcode.missing_string, ‘x’, null); assertequals(“could not find string parameter for –x.”, e.errormessage()); } public void testinvalidintegermessage() throws exception { argsexception e = new argsexception(argsexception.errorcode.invalid_integer, 312